---
title: "Chains 2"
output:
  html_notebook: default
  html_document: default
---

```{r opts}
library(knitr)
opts_chunk$set(echo = FALSE)
opts_chunk$set(include = TRUE)
opts_chunk$set(cache = FALSE)
opts_chunk$set(tidy = TRUE)
```

```{r data, message=FALSE}
library(ordinal)
library(effects)
library(ggplot2)
library(dplyr)
library(vcd)

comp11 <- read.csv('C:\\Users\\dbarron\\Dropbox\\Care Homes\\comp11.csv')
comp11$chapter1.old <- ordered(comp11$chapter1, levels = c('X', 'N','Y'))
comp11$chapter2.old <- ordered(comp11$chapter2, levels = c('X', 'N','Y'))
comp11$chapter3.old <- ordered(comp11$chapter3, levels = c('X', 'N','Y'))
comp11$chapter4.old <- ordered(comp11$chapter4, levels = c('X', 'N','Y'))
comp11$chapter5.old <- ordered(comp11$chapter5, levels = c('X', 'N','Y'))


comp11$chapter1.new <- ordered(comp11$chapter1, levels = c('I', 'R', 'G', 'O'))
comp11$chapter2.new <- ordered(comp11$chapter2, levels = c('I', 'R', 'G', 'O'))
comp11$chapter3.new <- ordered(comp11$chapter3, levels = c('I', 'R', 'G', 'O'))
comp11$chapter4.new <- ordered(comp11$chapter4, levels = c('I', 'R', 'G', 'O'))
comp11$chapter5.new <- ordered(comp11$chapter5, levels = c('I', 'R', 'G', 'O'))

comp11$chap1 <- ordered(comp11$chap1, levels = c('Inadequate', 'Poor', 'Good'))
comp11$chap2 <- ordered(comp11$chap2, levels = c('Inadequate', 'Poor', 'Good'))
comp11$chap3 <- ordered(comp11$chap3, levels = c('Inadequate', 'Poor', 'Good'))
comp11$chap4 <- ordered(comp11$chap4, levels = c('Inadequate', 'Poor', 'Good'))
comp11$chap5 <- ordered(comp11$chap5, levels = c('Inadequate', 'Poor', 'Good'))

```

```{r functions}

ef.plot <- function(m, term, title = NULL, response.name = term, conf.int = TRUE, ...){
  # Alternative to plots produced by the effects package, using ggplot2
  require(effects)
  require(ggplot2)
  
  if (!(class(m) %in% c('polr', 'clm', 'clmm'))) stop('Only works for polr or clm objects')
  if (!is.character(term)) stop('term must be a string')
  
  eftabs <- effect(term, m, ...)
  dta <- data.frame(eftabs$prob)
  dta.l <- data.frame(eftabs$lower.prob)
  dta.u <- data.frame(eftabs$upper.prob)
  names(dta) <- eftabs$y.levels
  names(dta.l) <- eftabs$y.levels
  names(dta.u) <- eftabs$y.levels
  
  dta <- suppressMessages(reshape2::melt(dta))
  dta.l <- suppressMessages(reshape2::melt(dta.l))
  dta.u <- suppressMessages(reshape2::melt(dta.u))
  
  k <- dim(eftabs$x)[1]
  n <- dim(dta)[1]
  
  if (is.null(levels(eftabs$x))){ # not a factor
    dta[, term] <- eftabs$x
  } else {
    dta[, term] <- gl(k, 1, n, labels = levels(eftabs$x[, 1]))
  }
  dta$Lower <- dta.l$value
  dta$Upper <- dta.u$value
  names(dta)[1:2] <- c(eftabs$response,'Probability')
  if (is.null(title)) title <- eftabs$response
  if (is.null(response.name)) response.name <- term
  g <- ggplot(dta, aes_string(x = term, y = "Probability", group = eftabs$response)) + 
    geom_point(colour = 'red', size = 3) +
    geom_line() + facet_grid(formula(paste(eftabs$response, "~ ."))) + theme(axis.text.x = element_text(size = 10)) + 
    theme_bw() + labs(title = title, x = response.name)
  
  if (conf.int) {
    g + geom_errorbar(aes(ymin = Lower, ymax = Upper), colour = 'darkgrey', width = 0.1) 
  } else g
    
}


```

```{r vars}
comp11$chain.type <- ifelse(comp11$Group_Size == 1, 'Independent',
                       ifelse(comp11$Group_Size > 1 & comp11$Group_Size <= 10, 'Small',
                          ifelse(comp11$Group_Size > 10 & comp11$Group_Size <= 70, 'Medium',
                            ifelse(comp11$Group_Size > 70, 'Large', NA))))
comp11$chain.type <- factor(comp11$chain.type)

comp11$chain.type2 <- ifelse(comp11$Group_Size == 1, 'Independent',
                       ifelse(comp11$Group_Size > 1 & comp11$Group_Size <= 10, 'Small',
                          ifelse(comp11$Group_Size > 10 & comp11$Group_Size <= 70, 'Medium',
                            ifelse(comp11$Group_Size > 70 & comp11$Group_Size <= 100, 'Large', 
                              ifelse(comp11$Group_Size > 100, 'Very Large', NA)))))
comp11$chain.type2 <- factor(comp11$chain.type2)


comp11$for_profit <- ifelse(comp11$sector == 'For-Profit', 'For-Profit', 'Non-Profit')

comp11$logChain_Size <- log(comp11$Group_Size)
comp11$Chain_Size_qk <- comp11$Group_Size^2 / 1000

dvs <- paste0('chap', 1:5)
dvs.old <- paste0('chapter', 1:5, '.old')
dvs.new <- paste0('chapter', 1:5, '.new')

```

# All cases

## In chain dummy

```{r dummy}
comp11.noLA <- filter(comp11, sector != 'Local Authority')

forms <- paste(dvs, '~ sector * In_Group + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m')
all.dummies <- lapply(forms, clm, data = comp11.noLA, Hess = TRUE)

lapply(1:5, function(x) all.dummies[[x]]$call <<- call('clm', formula = as.formula(forms[x]), data = quote(comp11.noLA), Hess = TRUE))

lapply(all.dummies, summary)
#beepr::beep(3)
```

## Size categories

```{r cats}
forms <- paste(dvs, '~ sector * chain.type + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m  + (1|care.home.group)')
all.cats <- lapply(forms, clmm, data = comp11, Hess = TRUE)

lapply(1:5, function(x) all.cats[[x]]$call <<- call('clmm', formula = as.formula(forms[x]), data = quote(comp11), Hess = TRUE))

lapply(all.cats, summary)
beepr::beep(3)
```

## Continuous

```{r cont}
forms <- paste(dvs, '~ sector * logChain_Size + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m + (1|care.home.group) ')

all.cont <- lapply(forms, clmm, data = comp11.noLA, Hess = TRUE)

lapply(1:5, function(x) all.cont[[x]]$call <<- call('clmm', formula = as.formula(forms[x]), data = quote(comp11.noLA), Hess = TRUE))

lapply(all.cont, summary)

```



# Excluding local authorities

## In chain dummy

```{r dummy2}

forms <- paste(dvs, '~ sector * In_Group + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m  + (1|care.home.group)')
all.dummies.nola <- lapply(forms, clmm, data = comp11, Hess = TRUE, subset = comp11$sector != 'Local Authority')

lapply(1:5, function(x) all.dummies.nola[[x]]$call <<- call('clmm', formula = as.formula(forms[x]), data = quote(comp11), Hess = TRUE, subset = quote(comp11$sector != 'Local Authority')))

lapply(all.dummies.nola, summary)
```

## Size categories

```{r cats2}
forms <- paste(dvs, '~ sector * chain.type + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m  ')
all.cats.nola <- lapply(forms, clm, data = comp11, Hess = TRUE, subset = comp11$sector != 'Local Authority')

lapply(1:5, function(x) all.cats.nola[[x]]$call <<- call('clm', formula = as.formula(forms[x]), data = quote(comp11), Hess = TRUE, subset = quote(comp11$sector != 'Local Authority')))

lapply(all.cats.nola, summary)
```

## Continuous

```{r cont2}
forms <- paste(dvs, '~ sector * logChain_Size + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m  + (1|care.home.group)')
all.cont.nola <- lapply(forms, clmm, data = comp11, Hess = TRUE, subset = comp11$sector != 'Local Authority')

lapply(1:5, function(x) all.cont.nola[[x]]$call <<- call('clmm', formula = as.formula(forms[x]), data = quote(comp11), Hess = TRUE, subset = quote(comp11$sector != 'Local Authority')))

lapply(all.cont.nola, summary)

```
# Versions without interactions

## In chain dummy

```{r dummy3}
forms <- paste(dvs, '~ sector + In_Group + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m  + (1|care.home.group)')
all.dummies.noint <- lapply(forms, clmm, data = comp11, Hess = TRUE)

lapply(1:5, function(x) all.dummies.noint[[x]]$call <<- call('clmm', formula = as.formula(forms[x]), data = quote(comp11), Hess = TRUE))

lapply(all.dummies.noint, summary)
beepr::beep(3)
```

## Size categories

```{r cats3vl}
forms <- paste(dvs, '~ sector + chain.type2 + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m  + (1|care.home.group)')
all.catsvl.noint <- lapply(forms, clmm, data = comp11, Hess = TRUE)

lapply(1:5, function(x) all.catsvl.noint[[x]]$call <<- call('clmm', formula = as.formula(forms[x]), data = quote(comp11), Hess = TRUE))

lapply(all.catsvl.noint, summary)
```


## Continuous

```{r cont3}
forms <- paste(dvs, '~ sector + logChain_Size + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m  + (1|care.home.group)')
forms <- paste(dvs, '~ sector + logChain_Size + Total.Beds.k + Age.k + purpose.built + dementia  + OVer.65.m')

all.cont.noint <- lapply(forms, clm, data = comp11, Hess = TRUE)

lapply(1:5, function(x) all.cont.noint[[x]]$call <<- call('clm', formula = as.formula(forms[x]), data = quote(comp11), Hess = TRUE))

lapply(all.cont.noint, summary)
plot(Effect('logChain_Size', all.cont.noint[[5]]))
```
```{r contquad}
forms <- paste(dvs, '~ sector + poly(Group_Size, degree = 2) + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m  + (1|care.home.group)')
forms <- paste(dvs, '~ sector + poly(Group_Size, degree = 2) + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m  ')

all.cont.q <- lapply(forms, clm, data = comp11, Hess = TRUE)

lapply(1:5, function(x) all.cont.q[[x]]$call <<- call('clm', formula = as.formula(forms[x]), data = quote(comp11), Hess = TRUE))

lapply(all.cont.q, summary)
plot(Effect('Group_Size', all.cont.q[[1]]))
```

# Excluding local authorities

## In chain dummy

```{r dummy4}

forms <- paste(dvs, '~ sector + In_Group + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m  + (1|care.home.group)')
all.dummies.nolaint <- lapply(forms, clmm, data = comp11, Hess = TRUE, subset = comp11$sector != 'Local Authority')

lapply(1:5, function(x) all.dummies.nolaint[[x]]$call <<- call('clmm', formula = as.formula(forms[x]), data = quote(comp11), Hess = TRUE, subset = quote(comp11$sector != 'Local Authority')))

lapply(all.dummies.nolaint, summary)
```

## Size categories

```{r cats4}
forms <- paste(dvs, '~ sector + chain.type + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m  + (1|care.home.group)')
all.cats.nolaint <- lapply(forms, clmm, data = comp11, Hess = TRUE, subset = comp11$sector != 'Local Authority')

lapply(1:5, function(x) all.cats.nolaint[[x]]$call <<- call('clmm', formula = as.formula(forms[x]), data = quote(comp11), Hess = TRUE, subset = quote(comp11$sector != 'Local Authority')))

lapply(all.cats.nolaint, summary)
```

## Continuous

```{r cont4}
forms <- paste(dvs, '~ sector + logChain_Size + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m + (1|care.home.group) ')
forms <- paste(dvs, '~ sector * logChain_Size + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m')
all.cont.nolaint <- lapply(forms, clm, data = comp11, Hess = TRUE, subset = comp11$sector != 'Local Authority')

lapply(1:5, function(x) all.cont.nolaint[[x]]$call <<- call('clmm', formula = as.formula(forms[x]), data = quote(comp11), Hess = TRUE, subset = quote(comp11$sector != 'Local Authority')))

lapply(all.cont.nolaint, summary)

```
# Null models
```{r null}
forms <- paste(dvs, '~ sector + Total.Beds.k + Age.k + purpose.built  + dementia  + OVer.65.m + (1|care.home.group) ')
all.null <- lapply(forms, clmm, data = comp11, Hess = TRUE, subset = comp11$sector != 'Local Authority')

lapply(1:5, function(x) all.null[[x]]$call <<- call('clmm', formula = as.formula(forms[x]), data = quote(comp11), Hess = TRUE, subset = quote(comp11$sector != 'Local Authority')))

lapply(all.null, summary)

```

# Test interactions

```{r inttest}
Map(anova, all.dummies, all.dummies.noint)
Map(anova, all.cats, all.cats.noint)
Map(anova, all.cont, all.cont.noint)

Map(anova, all.dummies.nola, all.dummies.nolaint)
Map(anova, all.cats.nola, all.cats.nolaint)
Map(anova, all.cont.nola, all.cont.nolaint)
```

# Effect plots

```{r plots}
lapply(all.dummies.noint, ef.plot, term = 'In_Group')

lapply(all.cats.noint, ef.plot, term = 'chain.type')

lapply(all.cont.noint, ef.plot, term = 'logChain_Size')

```
